### ISSUE TITLE
The problem with using Scrcpy is that the copied content on the phone cannot be transferred to the computer and cannot be pasted on the computer

### ISSUE THREAD

**Issue by puwei7788** [viarotel-org/escrcpy#201]
[server] ERROR: Could not invoke method
java.lang.NoSuchMethodException: android.content.IClipboard$Stub$Proxy.getPrimaryClip [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, int, int, boolean]
at java.lang.Class.getMethod(Class.java:2937)
at java.lang.Class.getMethod(Class.java:2449)
at com.genymobile.scrcpy.wrappers.ClipboardManager.getGetPrimaryClipMethod(ClipboardManager.java:64)
at com.genymobile.scrcpy.wrappers.ClipboardManager.getText(ClipboardManager.java:152)
at com.genymobile.scrcpy.Device.getClipboardText(Device.java:290)
at com.genymobile.scrcpy.Device$3.dispatchPrimaryClipChanged(Device.java:143)
at android.content.IOnPrimaryClipChangedListener$Stub.onTransact(IOnPrimaryClipChangedListener.java:84)
at android.os.Binder.execTransactInternal(Binder.java:1371)
at android.os.Binder.execTransact(Binder.java:1310)

——The above issues that occur during the use of Scrcpy prevent the copied content on the phone from being transmitted to the computer

**Comment by puwei7788** [comment]
The phone is Honor Magic5 (Android 14.0), and the computer is Thinkbook for Windows 11

**Comment by puwei7788** [comment]
scrcpy --mouse=sdk --keyboard=uhid 这样没用哈~
